spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: weeatnotificationservice@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: esercizio26092024
    secret:
      key:
    expiration: 18000000000000
  jpa:
    hibernate:
      dialect: jakarta.persistence.jdbc.url
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/project3
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
